### ISSUE TITLE
gw over remote connection: libGL error

### ISSUE THREAD

**Issue by lindenb** [kcleal/gw#7] opened 2022-11-29 13:13 UTC
Hi gw team,

I'm testing gw. I installed it via mamba. It looks like a library is missing in the package ? see below.

```
$ mamba create -y -n gw  -c bioconda gw
(...)
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

```
$ conda activate gw 
$ gw rotavirus_rf.fa -r RF01:100-1000 -b S1.bam

█▀▀ █ █ █
█▄█ ▀▄▀▄▀
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  255
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  162
  Current serial number in output stream:  163
```

thanks for your help.

**Comment by kcleal** [comment] 2022-11-29 13:33
Hi @lindenb,
This error has popped up before when using gw over a remote connection https://github.com/kcleal/gw/issues/3
Is this on your local machine?
libGL libraries are listed in the conda build, https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gw/meta.yaml, so Im not sure what is going wrong. If you are able to build manually this may solve the issue.

**Comment by lindenb** [comment] 2022-11-29 13:39
thanks for your quick answer

> Is this on your local machine?

no sorry, it's on our server

I'll try compile it.

**Comment by lindenb** [comment] 2022-11-29 13:43
module load gcc/9.3.0
$ make prep
"System: Linux"
(...)
$ make
g++ -g -Wall -std=c++17  -fno-common -dynamic -fwrapv -O3 -DNDEBUG -D LINUX -D __STDC_FORMAT_MACROS -g -I./include -I./src -I. -I./gw -I/usr/local/include -I./lib/skia -c src/drawing.cpp -o src/drawing.o
cc1plus: warning: unrecognized gcc debugging option: y
cc1plus: warning: unrecognized gcc debugging option: n
cc1plus: warning: unrecognized gcc debugging option: m
cc1plus: warning: unrecognized gcc debugging option: i
cc1plus: warning: unrecognized gcc debugging option: c
src/drawing.cpp:12:10: fatal error: GLFW/glfw3.h: No such file or directory
   12 | #include <GLFW/glfw3.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:85: src/drawing.o] Error 1
```

I'm missing some libraries (? aren't they installed with the conda env ?) and  think my compiler isn't the right one. Sorry, I won't have the time to explore this further.

**Comment by kcleal** [comment] 2022-11-29 14:04
Sorry for the issues. The conda lib and include directories are not found automatically. Here is a build recipe you can try:

    mamba install glfw htslib
    
    conda_lib=/home/kez/miniconda3/lib  # <-- change these!
    conda_include=/home/kez/miniconda3/include/
    
    git clone https://github.com/kcleal/gw.git
    cd gw && make prep
    CPPFLAGS+=-I${conda_include} LDLIBS+=-L${conda_lib} make
    gw --help

**Comment by lvelosuarez** [comment] 2023-03-03 10:49
Hi, I have a similar error when running qw in a server.
```bash
█▀▀ █ █ █
█▄█ ▀▄▀▄▀
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
gw: /home/conda/feedstock_root/build_artifacts/glfw_1658586347901/work/src/window.c:954: glfwSetWindowUserPointer: Assertion `window != ((void *)0)' failed.
```

Thanks for the input :)

**Comment by kcleal** [comment] 2023-03-03 11:07
Hi @lvelosuarez,
I also recently experienced this issue on a remote CentOS server. I believe it is caused by missing opengl drivers that skia relies on. Updating the os on our server fixed the issue for me, not an ideal fix sorry! What os is your server running?

**Comment by kcleal** [comment] 2023-03-05 17:42
Im guessing you are using a mac as your local machine?
I have managed to replicate this issue only when using local mac --> remote linux connection. I initially thought it was a libGL configuration issue, but now im thinking the issue might stem from Xquartz (some discussion about it here https://github.com/XQuartz/XQuartz/issues/144). I have tested gw remote in various configurations, ubuntu-local -> ubuntu-remote, and mac-local -> ubuntu-remote and I only found issues with mac - ubuntu. You might be able to get Xquartz working with the suggested fixes mentioned in that post, although these didnt work for me.
However, I did manage to get mac -> ubuntu working using the gw docker image. This bypasses xquartz altogether, but it is obviously a lot more hastle to use than I would like. 
To get this working you need to install xpra on your mac, then start gw docker (more detailed instructions here: https://hub.docker.com/repository/docker/kcleal/gw/general):
```
brew install --cask xpra
docker pull kcleal/gw
sudo docker run -it -p 9876:9876 kcleal/gw
```
Next open a browser and type in `0.0.0.0:9876`. You will see a terminal from inside the container, you can then use this to ssh to your ubuntu server and start gw. Not ideal though sorry.

<img width="1491" alt="Screenshot 2023-03-05 at 17 23 23" src="https://user-images.githubusercontent.com/42997789/222976557-f52e50f0-0dc9-420b-8946-eca74ab6369a.png">

**Comment by kcleal** [comment] 2024-01-31 23:23
Hopefully v0.9.3 has resolved this issue - skia and gw are now configured to use EGL api, which should bypass the issue. I will close this for now, but please re open if this issue persists

**Closed by kcleal** 2024-01-31 23:23 UTC
Labels: help wanted
