### ISSUE TITLE
segfault after typing `help`

### ISSUE THREAD

**Issue by jamestwebber** [kcleal/gw#42] opened 2024-07-29 14:50 UTC
**Describe the bug**
I was excited to try this out! But immediately hit a segfault after I loaded some BAM files and typed `/help`. 😢 

**To Reproduce**

I installed with `conda create -n gw -c bioconda gw`, ran `gw hg38` to start a session, dragged four BAMs into the window, and the typed `/help` to see the commands available.

**System (please complete the following information):**
 - GW version `1.0.0` (`bioconda/osx-64::gw-1.0.0-hfdcf749_0`)
 - OS: macOS Sonoma 14.5 (on an x86 MBP)

**Comment by BioFalcon** [comment] 2024-07-29 14:59
I am also experiencing this same issue, same kind of setup (macOS Sonoma on an Intel Processor), also for some weird reason when running GW it shows version v0.1.0 instead v1.0.0, probably a typo?

**Comment by kcleal** [comment] 2024-07-29 16:21
Hi @jamestwebber,
That's not good! Would you be able to install use the desktop app or brew instead of conda? There seems to be a few issues with the conda install at the moment. I will see if I can reproduce the error my end...

**Comment by jamestwebber** [comment] 2024-07-29 16:29
Unfortunately the installer doesn't work either because OS X won't let me open it (and our IT rules are too strict for me to override this).
<img width="372" alt="Screenshot 2024-07-29 at 12 27 52" src="https://github.com/user-attachments/assets/88f00b2d-1a94-483f-acb1-fd1502bf9e8f">

**Comment by jamestwebber** [comment] 2024-07-29 16:34
> Also, does it work if you drag and drop a single bam, then navigate to a region?

Also segfaults :/

**Comment by kcleal** [comment] 2024-07-29 17:01
Hi @BioFalcon,
Where do you see the v0.1.0?

**Comment by jamestwebber** [comment] 2024-07-29 17:22
I see it in the download link in the console:

` ▀ https://github.com/kcleal/ref_genomes/releases/download/v0.1.0`

Also, the brew installation segfaulted as well. I'll check back later!

**Comment by kcleal** [comment] 2024-07-29 17:36
Thanks for trying. The ref genomes v0.1.0 is related to the GitHub repo for the reference genomes, so is nothing to worry about.

I'm afraid I don't know why you have a segfault. If you could run the following test, it would be helpful for me:


`gw hg38 -r chr1 -n > /dev/null`

Also, if you have a local reference genome handy, would you be able to replace hg38 with the path to your reference genome? I'm wondering if the online reference genome is causing an issue



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by BioFalcon** [comment] 2024-07-30 13:53
I tried substituting to a local genome, still het the segmentation fault:

`zsh: segmentation fault  gw -b RepMasker.bed ce11.fa`

**Comment by kcleal** [comment] 2024-07-30 14:24
Ok thanks for trying. Are you also using intel macOS Sonoma @BioFalcon? I will have some time tomorrow to try and fix this.

**Comment by BioFalcon** [comment] 2024-07-30 17:02
Yes, Intel Mac with Sonoma

**Comment by kcleal** [comment] 2024-07-31 20:34
I managed to repeat this issue on an intel Mac where GW crashed if you type in a region ID or load a bam after start up. I have hopefully now fixed the issue in v1.0.1. I will need someone else to confirm if the issue is resolved. I was able to install a working version using conda on my macOS intel test machine.

**Comment by jamestwebber** [comment] 2024-07-31 20:51
It works! 🎉 Checking it out now, thanks for the fix.

**Closed** 2024-07-31 20:57 UTC
